package EchoApp;


/**
* EchoApp/Echo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EchoApp.idl
* Saturday, April 12, 2025 3:25:38 PM IST
*/

public interface Echo extends EchoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Echo
