package EchoApp;


/**
* EchoApp/EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EchoApp.idl
* Saturday, April 12, 2025 3:25:38 PM IST
*/

public interface EchoOperations 
{
  String echoString ();
} // interface EchoOperations
